export const DATA = [
  {
    id: 1,
    title: "Ticket Management",
    icon: "engineering",
    iconColor: "#fffcff",
    avatarColor: "#ff1e62",
    routeName: "ComplaintRegister",
  },
  {
    id: 5,
    title: "Room Management",
    icon: "headset-mic",
    iconColor: "#f2fff3",
    avatarColor: "#537186",
    routeName: "Profile",
  },
  {
    id: 6,
    title: "Asset Management",
    icon: "account-tree",
    iconColor: "#fffff5",
    avatarColor: "#6f70ee",
    routeName: "Profile",
  },
  {
    id: 7,
    title: "Feed Back Module",
    icon: "feedback",
    iconColor: "#fffcfd",
    avatarColor: "#0a7e88",
    routeName: "Profile",
  },
  {
    id: 8,
    title: "Incident Management",
    icon: "report-problem",
    iconColor: "#fcfdf7",
    avatarColor: "#f60381",
    routeName: "Profile",
  },
  {
    id: 9,
    title: "Central Request Management",
    icon: "speaker-notes",
    iconColor: "#fcfdf7",
    avatarColor: "#489428",
    routeName: "Profile",
  },
];
